### ISSUE TITLE
'00A9' what is it?

### ISSUE THREAD

**Issue by g-reno** [miracle2k/android2po#23]
$ a2po init zh_CN
'00A9'
'00A9'
   [created] locale/zh_CN.po
     [mkdir] res/values-zh-rCN
   [created] res/values-zh-rCN/strings.xml

I thought it was supposed to create:
   [created] locale/strings-zh_CN.po

No?

**Comment by brentinrochester** [comment]
The '00A9' is a unicode escape sequence that is echo'd to the screen.  This is normal, and can be ignored unless you see an error immediately following one.  Yours seem OK.

**Comment by miracle2k** [comment]
With Brent's fix this should no longer occur.
