### ISSUE TITLE
Babel-1.0dev isn't installable because "elsdoerfer.name" is down

### ISSUE THREAD

**Issue by mahata** [miracle2k/android2po#33]
Hi,

It seems `python setup.py install` fails with the following message:

```
Downloading http://elsdoerfer.name/download/android2po/files/Babel-1.0dev.tar.gz
error: http://elsdoerfer.name/download/android2po/files/Babel-1.0dev.tar.gz returned a bad status line. The server might be down, 
```

I think it's possible to modify `setup.py` to install the latest Babel, but I think `elsdoerfer.name` is your own domain. Can you fix it? Or should I locally modify `setup.py` to download the latest version of Babel?

Thanks,

**Comment by miracle2k** [comment]
Grr. Thanks, fixed.

**Comment by mahata** [comment]
Yay! Thanks :+1:

**Comment by jefstr** [comment]
Hi, this appears to be broken again.

**Comment by miracle2k** [comment]
Sorry about that.
