### ISSUE TITLE
Travis CI builds are not being built

### ISSUE THREAD

**Issue by kruton** [miracle2k/android2po#37]
It looks like the Travis-CI builds are not proceeding: https://travis-ci.org/miracle2k/android2po

You'll probably have to sign into Travis-CI to renew the OAuth scope: https://travis-ci.org/auth

**Comment by kruton** [comment]
Additionally, you'll have to set up a coveralls.io account to get Coveralls working.

**Comment by miracle2k** [comment]
It seems it was disabled in the repo config, not sure why. Let's see what happens.

**Comment by kruton** [comment]
coveralls.io still needs to be setup for the "cover" build to succeed.
