### ISSUE TITLE
fy-NL is not a valid locale

### ISSUE THREAD

**Issue by pocmo** [miracle2k/android2po#51]
One of ours apps is getting localized to Frisian (Netherlands), locale: fy-NL. However importing/exporting fails with:

`[failed] fy-NL is not a valid locale`

**Comment by hansfn** [comment]
This problem is not present in android2po 1.5.0 with babel 2.5.3. The requirements file is locking babel to 1.3 so maybe that is the problem.

Please verify my findings and close the issue if you agree.

**Comment by pocmo** [comment]
This doesn't seem to happen anymore.
