### ISSUE TITLE
Not emitting empty items in string-array

### ISSUE THREAD

**Issue by brentinrochester** [miracle2k/android2po#64]
It is valid for an item in a string-array to be empty.  The parser will accept a self-closing tag, but it is more common to find: 
`<item></item>`

This is commonly used. You can see an [example from AOSP source](https://android.googlesource.com/platform/packages/apps/Settings/+/9d91d19df7e2cb044716b8d7c11d47134a523644/res/values/arrays.xml ) that uses this technique multiple times.

However, a2po will omit those with a warning.  Then the string-array is missing an item.  If run on the case in the provided example, this causes the remaining values to correlate with the wrong array index, and thus the wrong status is displayed. 

It is critical that empty items be emitted in the original location within a string-array.

**Comment by miracle2k** [comment]
So I think this was fixed in #64, yes? Closing it then. Thanks for the patch!
